### ISSUE TITLE
escape 함수 개선

### ISSUE THREAD

**Issue by xdoju** [hhosu107/Compiler#3]
escape 함수는 몇몇 문자를 출력할 수 있는 형태로 고쳐 주는 함수인데, 종료 조건이 '\0' 으로 되어 있어서 \0 이후에도 문자열이 지속될 경우 출력을 못 함.

ex. `"abcd\\\\\n\n\0\\\\"`

**Comment by hhosu107** [comment]
string에 저렇게 넣으면 \0 뒤의 것들은 그냥 날아가는 것으로 기억함.(C/C++ 기준)
그렇다면 \0를 읽는 순간 그 뒤의 내용들(doule qoute 나오기 전까지)을 삭제하는 게 필요해 보이는데...
 그걸 \0 나왔다고 바로 string token으로 끊어버리고 주기에는 "...\0.. ("로 닫히지 않은) 등의 invalid string이 있을 것 같다.
그러면 저 경우에는 "X\0Y" 라고 했을 때 "X\0"만 token의 value로 들어가게 한 다음 "를 탐색해서 있다면 token을 전달하고 없다면 전체를 tUndefined로 전달하는 방법이 있을 수 있겠다. 그렇긴 한데 eTL에 퀴리를 날려보는 게 더 정확할 듯.
